### ISSUE TITLE
snapshot_add

### ISSUE THREAD

**Issue by lingyiba** [yaoniplan/note#8]
* sudo timeshift --list # list snapshots (If you don't have timeshift, please install timeshift)
* sudo timeshift --create # create a snapshot
* sudo timeshift --restore # restore a snapshot
* sudo timeshift --delete # delete a snapshot
* ***Reference***
* [timeshift man](https://linuxcommandlibrary.com/man/timeshift)

**Comment by yaoniplan** [comment]
I will test it for 24 hours.

**Comment by yaoniplan** [comment]
`sudo timeshift --restore`
* I had try it just now, but it don't work.
* ![image](https://user-images.githubusercontent.com/104973099/190420696-0e79bae6-1f8f-4c12-bb76-ce56d7e9d971.png)
* I'll continue testing it for 24 hours.

**Comment by yaoniplan** [comment]
1. `snapper -c <your_snapper_config_name> create-config <your_subvolume_path>` # Creating a new configuration.
2. `snapper -c <your_snapper_config_name> create --description=your_description -p` # Creating a new snapshot.
3. `snapper -c <your_snapper_config_name> undochange number1..number2` # Undo changes done between snapshot "number1" and "number2".
4. `systemctl enable snapper-timeline.timer` # Auto creating snapshots.
5. `systemctl enable snapper-cleanup.timer` # Auto clean snapshots.
* ***Note***
* When you get "creating btrfs subvolume .snapshots failed since it already exists", you can try it.
* `sudo vim /etc/conf.d/snapper`
* You should edit it. And for example:
```
## Path: System/Snapper

## Type:        string
## Default:     ""
# List of snapper configurations.
SNAPPER_CONFIGS="root home data"
```
* ***Reference***
* ["creating btrfs subvolume .snapshots failed since it already exists" When trying to REcreate a old config. #408](https://github.com/openSUSE/snapper/issues/408)
* [用 snapper 轻松玩转 Btrfs 的快照功能](https://zhuanlan.zhihu.com/p/31082518)

**Comment by yaoniplan** [comment]
Addtional:
* `sudo umount /.snapshots`
* `sudo rm -rf /.snapshots`
* `sudo snapper -c <name> create-config /`
* `sudo snapper -c <name> create --description=your_description -p`
* `sudo snapper -c <name> list`
* `sudo snapper -c <name> undochange <number_next>..<number_previous>`
* `systemctl enable snapper-timeline.timer`
* `systemctl enable snapper-cleanup.timer`

**Comment by yaoniplan** [comment]
I'll continue it.
* ***References***
* [SysadminGuide - btrfs Wiki](https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Snapshots)
* [BTRFS Snapshots, how do you restore?](https://www.reddit.com/r/archlinux/comments/qx6ip3/btrfs_snapshots_how_do_you_restore/)

**Comment by yaoniplan** [comment]
https://github.com/yaoniplan/note/blob/master/journals/2023-02-17.md # done
